/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analysis-results`; params?: Router.UnknownInputParams; } | { pathname: `/crop-stages`; params?: Router.UnknownInputParams; } | { pathname: `/crop-types`; params?: Router.UnknownInputParams; } | { pathname: `/fertilizer-selection`; params?: Router.UnknownInputParams; } | { pathname: `/gobh-instructions`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/image-analysis`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/instruction-nitrogen`; params?: Router.UnknownInputParams; } | { pathname: `/instructions`; params?: Router.UnknownInputParams; } | { pathname: `/nitrogen-calculator`; params?: Router.UnknownInputParams; } | { pathname: `/pre-planting-instructions`; params?: Router.UnknownInputParams; } | { pathname: `/results`; params?: Router.UnknownInputParams; } | { pathname: `/rice-tutorial`; params?: Router.UnknownInputParams; } | { pathname: `/selection`; params?: Router.UnknownInputParams; } | { pathname: `/sprout-instructions`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/analysis-results`; params?: Router.UnknownOutputParams; } | { pathname: `/crop-stages`; params?: Router.UnknownOutputParams; } | { pathname: `/crop-types`; params?: Router.UnknownOutputParams; } | { pathname: `/fertilizer-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/gobh-instructions`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/image-analysis`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/instruction-nitrogen`; params?: Router.UnknownOutputParams; } | { pathname: `/instructions`; params?: Router.UnknownOutputParams; } | { pathname: `/nitrogen-calculator`; params?: Router.UnknownOutputParams; } | { pathname: `/pre-planting-instructions`; params?: Router.UnknownOutputParams; } | { pathname: `/results`; params?: Router.UnknownOutputParams; } | { pathname: `/rice-tutorial`; params?: Router.UnknownOutputParams; } | { pathname: `/selection`; params?: Router.UnknownOutputParams; } | { pathname: `/sprout-instructions`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/analysis-results${`?${string}` | `#${string}` | ''}` | `/crop-stages${`?${string}` | `#${string}` | ''}` | `/crop-types${`?${string}` | `#${string}` | ''}` | `/fertilizer-selection${`?${string}` | `#${string}` | ''}` | `/gobh-instructions${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/image-analysis${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/instruction-nitrogen${`?${string}` | `#${string}` | ''}` | `/instructions${`?${string}` | `#${string}` | ''}` | `/nitrogen-calculator${`?${string}` | `#${string}` | ''}` | `/pre-planting-instructions${`?${string}` | `#${string}` | ''}` | `/results${`?${string}` | `#${string}` | ''}` | `/rice-tutorial${`?${string}` | `#${string}` | ''}` | `/selection${`?${string}` | `#${string}` | ''}` | `/sprout-instructions${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analysis-results`; params?: Router.UnknownInputParams; } | { pathname: `/crop-stages`; params?: Router.UnknownInputParams; } | { pathname: `/crop-types`; params?: Router.UnknownInputParams; } | { pathname: `/fertilizer-selection`; params?: Router.UnknownInputParams; } | { pathname: `/gobh-instructions`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/image-analysis`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/instruction-nitrogen`; params?: Router.UnknownInputParams; } | { pathname: `/instructions`; params?: Router.UnknownInputParams; } | { pathname: `/nitrogen-calculator`; params?: Router.UnknownInputParams; } | { pathname: `/pre-planting-instructions`; params?: Router.UnknownInputParams; } | { pathname: `/results`; params?: Router.UnknownInputParams; } | { pathname: `/rice-tutorial`; params?: Router.UnknownInputParams; } | { pathname: `/selection`; params?: Router.UnknownInputParams; } | { pathname: `/sprout-instructions`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
